### ISSUE TITLE
Global headers overwrite

### ISSUE THREAD

**Issue by MadUser** [auth0/angular2-jwt#117]
when creating global headers in the constructor they will be overwritten.

example:

```
export const AUTH_PROVIDERS: any = [
    provide(AuthHttp, {
        useFactory: (http: Http, options: RequestOptions, router: Router) => {
            return new AuthHttp(new AuthConfig(), http, router, new RequestOptions({headers: new Headers({'Content-Type': 'application/json', 'Some-Key': 'Some-value'})})
            );
        },
        deps: [Http, RequestOptions, Router]
    })
];
```

you should fix this function:

```
    private mergeOptions(defaultOpts: RequestOptions, providedOpts: RequestOptionsArgs) {
        let newOptions = defaultOpts || new RequestOptions();
        newOptions = newOptions.merge(new RequestOptions(providedOpts));
        if (this._config.globalHeaders) {
            this.setGlobalHeaders(this._config.globalHeaders, providedOpts);
        }

        return newOptions;
    }

```

as you can see, I moved the the merging line before setting the headers.
this is from the angular docs:

``````
 /**
     * Creates a copy of the `RequestOptions` instance, using the optional input as values to override
     * existing values. This method will not change the values of the instance on which it is being
     * called.
     *
     * **Note that `headers` and `search` will override existing values completely if present in
     * the `options` object. If these values should be merged, it should be done prior to calling
     * `merge` on the `RequestOptions` instance.**
     *
     * ### Example ([live demo](http://plnkr.co/edit/6w8XA8YTkDRcPYpdB9dk?p=preview))
     *
     * ```typescript
     * import {RequestOptions, Request, RequestMethod} from '@angular/http';
     *
     * var options = new RequestOptions({
     *   method: RequestMethod.Post
     * });
     * var req = new Request(options.merge({
     *   url: 'https://google.com'
     * }));
     * console.log('req.method:', RequestMethod[req.method]); // Post
     * console.log('options.url:', options.url); // null
     * console.log('req.url:', req.url); // https://google.com
     * ```
     */
    merge(options?: RequestOptionsArgs): RequestOptions;
``````

**Comment by chenkie** [comment]
Thanks. Why is it that you're putting your headers in `RequestOptions` and not in `AuthConfig`? Global headers should be registered in `AuthConfig`.

**Comment by MadUser** [comment]
I just prefer a plain and simple bootstrap  :-)
btw, I liked your module, I just had to add another function to set the token for the first time (encapsulation),
and another option to navigate to a login route on 401 instead of throwing an error (this is a big part of enhancing the HTTP to me) .
thanks for this helpful module.

**Comment by achimha** [comment]
+1

`AuthHttp` should behave like `Http`.

PS: `AUTH_PROVIDERS` uses the deprecated format with `provide()`, should be updated to use the object syntax:
```
{
   provide: AuthHttp,
 ...
}
```

**Comment by achimha** [comment]
I believe this issue is not solved yet. The problem is that `RequestOptions.merge` does not merge headers, it overrides them. If you provide a custom `RequestOptions` via dependency injection, its headers will be overridden by the empty headers object

https://angular.io/docs/ts/latest/api/http/index/RequestOptions-class.html

> Note that headers and search will override existing values completely if present in the options object. If these values should be merged, it should be done prior to calling merge on the RequestOptions instance.

The merge function should therefore manually merge the headers before calling merge:
```
private mergeOptions(defaultOpts: RequestOptions, providedOpts: RequestOptionsArgs) {
    let newOptions = defaultOpts || new RequestOptions();
    if (this._config.globalHeaders) {
      this.setGlobalHeaders(this._config.globalHeaders, providedOpts);
    }

    newOptions = newOptions.merge(new RequestOptions(providedOpts));

    return newOptions;
  }
```

**Comment by lewiswebber** [comment]
+1 on AuthHttp should behave like Http:
Make `application/json` the default `Content-Type`. JSON.stringify objects by default.

**Comment by elvirdolic** [comment]
In the current implementation, the per request header should override the global header if set explitiy. Currently the headers are merged, but if you want to override one special global defined header for one special request it's not possible.

let contentHeaders = new Headers();
        contentHeaders.set('Content-Type', 'application/x-www-form-urlencoded; charset=utf-8');

this wan't override the globalHeaders: [{'Content-Type':'application/json'}, as headers are merged. 

If same header is present it should be overriden from the per request header. Appending headers works as expected.

**Comment by giorgiofellipe** [comment]
As @elvirdolic well said, global headers should be overridable by per request headers...

**Comment by achimha** [comment]
Any update on this? It's a pretty fundamental flaw that cannot be worked around and it deviates from the behavior of Angular's `Http` class.

**Comment by escardin** [comment]
I would appreciate some tests demonstrating the problems, and possibly a PR fixing them.

Does the problem persist if you don't use global headers? Personally, I think global headers is a mis-feature. You can setup http itself to provide headers that are added to each request, and if that is insufficient you should have a wrapper around http/authhttp that adds them. Adding non-auth related headers to the request doesn't really fit within the purview of an authentication lib.

Technically, the HTTP spec allows for multiple headers of the same type (i.e. multiple Content-Type) and as such, global headers should be doing the right thing as per @elvirdolic. My reading of the code indicates that individual headers are replaced rather than appended; at least, that's what I recall `Headers.set()` doing (append would be `Headers.add()`).

@achimha It is my intent that AuthHttp is a drop in replacement for Http, however a number of different ways to add 'global headers' have snuck in, and they all behave differently. Defaultoptions (on the AuthHttp constructor) just applies an http.merge with your request. GlobalHeaders iterates and sets each one in the request individually. Afaik http's merge just takes the entire headers object of the primary request object and drops the one from the secondary request object (This is probably why globalheaders exists).

Ugh, reading through the code again after a while, I can see tons of issues from something that was once very very careful to behave exactly like Http, only adding an Auth header with your token. PRs with fixes and/or test cases (failing ones without fixes is fine) are welcome. At some point I will get around to reworking this lib to be more flexible and to behave more in line with http. When I get to the part about headers, I will post here. If there haven't been any posts, then there haven't been any changes.
