### ISSUE TITLE
Multiple Auth tokens. 

### ISSUE THREAD

**Issue by vespertilian** [auth0/angular2-jwt#141]
Just wondering if you are open to the idea of having multiple tokens configurable.

My need is to have both an authorization token and an impersonation token set. Currently it's only possible to set one dynamic token. By dynamic I mean one that get's the token from local storage on each request. You can set any number of static headers when the class is initialized. 

I was thinking this type of thing: 

``` js
    this.headerName = config.headerName || 'Authorization';
    if (config.headerPrefix) {
      this.headerPrefix = config.headerPrefix + ' ';
    } else if (config.noTokenScheme) {
      this.headerPrefix = '';
    } else {
      this.headerPrefix = 'Bearer ';
    }
    this.noJwtError = config.noJwtError || false;
    this.noTokenScheme = config.noTokenScheme || false;
    this.tokenGetter = config.tokenGetter || (() => localStorage.getItem(this.tokenName));
    this.tokenName = config.tokenName || 'id_token';
```

You could allow an array of objects to configure tokens. 

If you are interested I can try to put something together.

**Comment by escardin** [comment]
You can have as many as you want. Have multiple instances of AuthHttp with different token getters. Use an opaque token to reference them.

**Comment by vespertilian** [comment]
@escardin

Unfortunately I need to pass both tokens in the same request so I need to configure the same service with two tokens.

**Comment by escardin** [comment]
two jwt tokens in a single request? With multiple auth headers?

**Comment by vespertilian** [comment]
Yep!




On Wed, Aug 31, 2016 at 6:23 PM +0100, "escardin" <notifications@github.com> wrote:












two jwt tokens in a single request? With multiple auth headers?

**Comment by escardin** [comment]
What is the request supposed to look like (the raw http request, not the angular bit)?

**Comment by vespertilian** [comment]
This is what it looks like as a request header in dev tools: 

authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IlJjZGhQTjVmS0RwQ1BNeFY4YkstekU2XzJCZyIsImtpZCI6IlJjZGhQTjVmS0RwQ1BNeFY4YkstekU2XzJCZy.....

authorization-impersonation:
eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IlJjZGhQTjVmS0RwQ1BNeFY4YkstekU2XzJCZyIsImtpZCI6IlJjZGhQTjVmS0RwQ1BNeFY4Y.....

I have a hacked up version of Angular2-JWT but I was hoping to get a solution into this version so I can just NPM install any updates / bug fixes. 

It's just another header, both of them need to look for the token in local storage. Which is why I cannot set it as another generic static header (I tried it chokes on the `global.headers.forEach`)

**Comment by escardin** [comment]
I think I would write a wrapper around AuthHttp for that (at least for the second header). You could use Angular2-JWT as a base. A lot of the complexity in this lib is due to not being able to account for all the various ways people would want to use this lib. Your own implementation should be substantially simpler.

Ideally Http/AuthHttp would be easily composable and you could have two nested AuthHttp instances to solve your problem.

I really don't want the lib to get more complicated than it needs to be. I personally think it's too complicated as it is. I could see fitting in multiple token/header pairs if the current usage, new usage, and the code was as simple or simpler than it is today (and no breaking changes). I'm loathe to add tons of `typeof token === 'Array'` conditionals. It always makes it more work to understand what is usually otherwise a simple and clear function.

**Comment by vespertilian** [comment]
Yeah, 

I agree adding complexity is bad. I think if you could see what I am thinking you might be ok with it. I will just get a sample together and link you to it, as this has been a very abstract discussion so far.

**Comment by escardin** [comment]
I'm not going to discourage PRs, especially ones with tests.

**Comment by escardin** [comment]
Is this still an issue? Please reopen or file a new issue if so.
