### ISSUE TITLE
Using tokenNotExpired on Ionic 2: ORIGINAL EXCEPTION: token.split is not a function

### ISSUE THREAD

**Issue by karlpatrickespiritu** [auth0/angular2-jwt#196]
When using `tokenNotExpired` in Ionic 2 (`ionic-angular 3.10.8`), I'm getting a `token.split is not a function` error everytime. Did I miss something? I'm just following the straightforward example on the docs.

![image](https://cloud.githubusercontent.com/assets/10472504/19378192/dfe66604-921d-11e6-98e4-4cb91d81e3ca.png)

Simplified copy of my code:
````javascript
import { Storage } from '@ionic/storage';
import { tokenNotExpired } from 'angular2-jwt';
.....
@Component({
    selector: 'login',
    templateUrl: 'login.component.html',
    providers: [
        ... 
        Storage
    ]
})
export class LoginComponent {
....
    constructor(private storage: Storage) {
        // this throws: ORIGINAL EXCEPTION: token.split is not a function
        console.log(
           tokenNotExpired(null, this.storage.get('id_token'))
         );
    }
}
````

**Comment by MateuLlull** [comment]
I have the same issue. This issue happens when you send to the `tokenNotExpired` a `Promise` instead of `String`. The `Storage` package of Ionic2 RC0 returns a Promise, not a String, so the only way to handle it is working with Promises:

```js
this.storage.get('id_token').then(token => {
    console.log(tokenNotExpired(null, token)); // Returns true/false
});
```

The next step is return this True/False result to `*ngIf="auth.authenticated()"`, but I didn't found how to do it, maybe someone can help us.
 
P.S.: I just come to this repo to publish this same issue, so I subscribe to this thread.

**Comment by karlpatrickespiritu** [comment]
Tried your solution @MateuLlull, but i'm getting this error.

![image](https://cloud.githubusercontent.com/assets/10472504/19423467/2318fb26-9453-11e6-9439-068da18392ab.png)

**Comment by karlpatrickespiritu** [comment]
That definitely removed the error @MateuLlull. The docs must not be updated.

This should also work:

````javascript
tokenNotExpired('id_token');
````

The only thing left for me is that even though I already set the token in the local storage by doing:

````javascript
this.storage.set('id_token', token);
````

the `tokenNotExpired` always returns `false`.

**Comment by MateuLlull** [comment]
> The only thing left for me is that even though I already set the token in the local storage by doing:
> `this.storage.set('id_token', token);`
> the tokenNotExpired always returns false.

This issue maybe is because the *angular2-jwt* works with `localStorage` and now the *Ionic2 Storage* works in a different way.

See the docs (https://github.com/auth0/angular2-jwt#configuation-for-ionic-2) and look for `tokenGetter` config. This must work, but no way for me, the only code that works is the one that I shared with you in the first post. My problem still the same, return an *async* (async because it is a promise-related return) value to the **ngIf** directive.

**Comment by chenkie** [comment]
One thing you could do is get the token from`storage` and save it in the app's state when it starts up. Then you can pass this to `tokenNotExpired`. There's more token management in the auth service using this method, but it works: https://github.com/auth0-samples/auth0-ionic2-samples/blob/master/01-Login/src/services/auth/auth.service.ts

We'll be refactoring the lib and one thing we can likely do is allow `tokenNotExpired` to handle promises like how the `tokenGetter` has support for them.

**Comment by gfviegas** [comment]
Please see #185

**Comment by MateuLlull** [comment]
Thank's @chenkie, this is the shortest way to handle it. :+1:

**Comment by karlpatrickespiritu** [comment]
Thank you @chenkie. That worked.

Well, to sum it all up. We can use Ionic's storage by setting the `tokenGetter` using the factory pattern in our `@NgModule`. Rather than using the `localStorage`.  Which is documented [here](https://github.com/auth0/angular2-jwt#configuation-for-ionic-2).

And when using `tokenNotExpired` in Ionic, we should pass the token string in the second parameter rather than passing a promise. See @mateullull's [comment](https://github.com/auth0/angular2-jwt/issues/196#issuecomment-253753839)

Thanks guys!

**Comment by karlpatrickespiritu** [comment]
#205

**Comment by karlpatrickespiritu** [comment]
#205
