### ISSUE TITLE
Webpack warning: Cannot find source file 'angular2-jwt.ts':

### ISSUE THREAD

**Issue by dev-bro** [auth0/angular2-jwt#260]
I've installed latest version and have this error:
```
WARNING in ./~/angular2-jwt/angular2-jwt.js
Cannot find source file 'angular2-jwt.ts': Error: Cannot resolve 'file' or 'directory' ./angular2-jwt.ts in node_modules/angular2-jwt
```
Why do you ignore `*.ts` files for npm ?

**Comment by pandawi** [comment]
Experiencing this problem too. I've used `webpackMiddleware: { quiet: true }` to hide this for now but this is not a solution.

**Comment by Tuizi** [comment]
In fact the problem is in the source map file not with the ignore of `*.ts` I think.
In `angular2.jwt.js.map`, replacing `angular2-jwt.ts` by `angular2-jwt.d.ts` solve the issue.

**Comment by escardin** [comment]
See #218 and #198 for more info.

I'm open to fixes that aren't just re-including the .ts files. Angular doesn't include them and as such we shouldn't need to either. I assume we're screwing something up somewhere with what we push to npm. Part of my plans for 1.0 is to have test projects with the major ways of building angular (webpack, system, cli, ionic) so that issues like this can be found and prevented at build time. I doubt I will resolve this one myself before then.

**Comment by Tuizi** [comment]
@escardin You are absolutely right, `.ts` files should not be included. If you check the PrimeNG project for Angular 2 they doesn't include `.ts` files, only `.d.ts` like this repository and everything works fine.

The solution is to change the reference to the `.ts` file by the `.d.ts` in the **sourcemap** file.

**Comment by escardin** [comment]
I'll look at what primeNG does to do the source mapping when I work on this. Angular is a good example of what the end result should be, but imo is terrible as an example for how to do it, because their build is super complicated.

**Comment by lommez** [comment]
Did you guys find a solution for that issue?

**Comment by Adeola13** [comment]
`npm install angular2-jwt`
did the trick for me
