### ISSUE TITLE
AUTH_PROVIDERS

### ISSUE THREAD

**Issue by dchinn** [auth0/angular2-jwt#268]
Using angular 2, and the angular command line interface.

Per the instructions, in app.module.ts,  I imported 

    import { AUTH_PROVIDERS } from 'angular2-jwt';

and down below, in providers:

    providers: [AUTH_PROVIDERS]

But, when i try to serve the application ('ng serve'), I get the following error:

>ERROR in Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler (position 79:22 in the original .ts file), resolving symbol AUTH_PROVIDERS in [MYPROJECT]/node_modules/angular2-jwt/angular2-jwt.d.ts, resolving symbol AppModule in [MYPROJECT]/src/app/app.module.ts, resolving symbol AppModule in [MYPROJECT]/src/app/app.module.ts

"line 79:220 in the original .ts file" seems to point to angular2-jwt.d.ts, and i see that the line is declaring constant AUTH_PROVIDERS: Provider[]).  I'm not very good at javascript; is this supposed to be initialized to someting?

thanks in advance

**Comment by chenkie** [comment]
The readme needs to be updated to remove those instructions. Can you try with a factory function?

```ts
export function authHttpServiceFactory(http: Http, options: RequestOptions) {
  return new AuthHttp(new AuthConfig({
    tokenName: 'token',
          tokenGetter: (() => localStorage.getItem('token')),
          globalHeaders: [{'Content-Type':'application/json'}],
     }), http, options);
}

@NgModule({
  // ...

  providers: [
    // ...
    {
      provide: AuthHttp,
      useFactory: authHttpServiceFactory,
      deps: [Http, RequestOptions]
    }
  ]
})
```

**Comment by stefandb** [comment]
Thank you @chenkie. Your solution works

**Comment by JimiC** [comment]
@chenkie You are a life saver. Exactly the solution I was looking for.

**Comment by kartikgreen** [comment]
Hi, May i know where should this line be placed?

**Comment by JimiC** [comment]
@kartikgreen 
> export function authHttpServiceFactory(http: Http, options: RequestOptions) {
  return new AuthHttp(new AuthConfig({
    tokenName: 'token',
          tokenGetter: (() => localStorage.getItem('token')),
          globalHeaders: [{'Content-Type':'application/json'}],
     }), http, options);
}
Following standard coding guidelines this should go in its own file (i.e. `authHttpServiceFactory.ts`)

You then reference it in `app.module.ts` and you modify the `@NgModule` section accordingly.

**Comment by kartikgreen** [comment]
Thanks for your swift reply. i'am quite new to angular2. As per your guidance, I have create a file called authHttpServiceFactory.ts and pasted these lines of code in it,
import { Http, RequestOptions } from '@angular/http';
import { AuthHttp, AuthConfig, provideAuth } from 'angular2-jwt';
export function authHttpServiceFactory(http: Http, options: RequestOptions) {
  return new AuthHttp(new AuthConfig({
    tokenName: 'token',
          tokenGetter: (() => localStorage.getItem('token')),
          globalHeaders: [{'Content-Type':'application/json'}],
     }), http, options);
}

Should this function be in a class? what should i add in ngmodule?

**Comment by JimiC** [comment]
@kartikgreen Usage of `class` comes down to personal preference. Some use them, some don't. Experience will let you know when and where to use it.

In `NgModule` you add the related code snippet in `providers`.

**Comment by kartikgreen** [comment]
for the clarification here is my app.module.ts,
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { HumanComponent } from './human.component';
import { AppComponent } from './app.component';
import { AUTH_PROVIDERS, AuthHttp } from 'angular2-jwt';
import { Http, RequestOptions } from '@angular/http';

import { Auth } from './services/auth.service';
import { HomeComponent } from './components/home/home.component';
import { ProfileComponent } from './components/profile/profile.component';
import { authHttpServiceFactory } from './authHttpServiceFactory';
// require for routing
import { routing, appRoutingProviders } from './app.routing'

@NgModule({
  declarations: [
    AppComponent,
    HumanComponent,
    ProfileComponent,
    HomeComponent,
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    routing
  ],
  providers: [
    appRoutingProviders,
    AUTH_PROVIDERS,
    Auth,
    {
      provide: AuthHttp,
      useFactory: authHttpServiceFactory,
      deps: [Http, RequestOptions]
    }
    ],
  bootstrap: [AppComponent]
})

export class AppModule { }

i still get the same error,
ERROR in Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler (position 80:22 in the original .ts file), resolving symbol AUTH_PROVIDERS in /usr/src/app/node_modules/angular2-jwt/angular2-jwt.d.ts, resolving symbol AppModule in /usr/src/app/src/app/app.module.ts, resolving symbol AppModule in /usr/src/app/src/app/app.module.ts

**Comment by JimiC** [comment]
The snippets purpose is to replace `AUTH_PROVIDERS` usage.

**Comment by kartikgreen** [comment]
love you jimi. It worked.

**Comment by escardin** [comment]
@dchinn Did this resolve your problem? Please reopen if not.

**Comment by EdwardMCastrillon** [comment]
@chenkie Your solution does'nt works fine for me. When i trying to use a factory function i get the follow error: 

**Error: Error encountered resolving symbol values statically. Calling function ‘omakeDecorator’, function calls are not supported. Consider replacing the function or lambda with a reference to an exported function**
