### ISSUE TITLE
isTokenExpired incorrect calculation

### ISSUE THREAD

**Issue by lukaszwilk** [auth0/angular2-jwt#272]
I've noticed a problem with checking token expiry date in isTokenExpired method. Token I've been using has exp set to 1484425965097. Full token below.

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM3LCJ1c2VyVHlwZUlkIjoyLCJleHAiOjE0ODQ0MjU5NjUwOTcsImlhdCI6MTQ4NDQyNTkwNX0.4lZbTBN52pIoILeR5s-nfMRZ46igRftcEeE00EpyL98

```
var date = new Date(0);
date.setUTCSeconds(decoded.exp);
date.valueOf()
```
Above part of code returns 1484425965097**000** (GMT: Sat, 14 Jan 2017 20:32:45 GMT). Please notice three zeros at the end,

```
(new Date().valueOf() + (offsetSeconds * 1000))
```
This part gives 1484427908208 (GMT: Sat, 14 Jan 2017 21:05:08.208 GMT)

```
!(date.valueOf() > (new Date().valueOf() + (offsetSeconds * 1000)))
```
If we were comparing parsed dates then token is obviously outdated but since timestamps are compared here, then 1484425965097**000** is still larger value then 1484427908208 and it provides incorrect result (token not expired).

**Comment by escardin** [comment]
So, you're sending a timestamp with millisecond accuracy and we're expecting only second accuracy, and converting it to millisecond scale? You should only be sending second accuracy as per the [RFC](https://tools.ietf.org/html/rfc7519):

>NumericDate
> 
>       A JSON numeric value representing the number of seconds from
>       1970-01-01T00:00:00Z UTC until the specified UTC date/time,
>       ignoring leap seconds.  This is equivalent to the IEEE Std 1003.1,
>       2013 Edition [POSIX.1] definition "Seconds Since the Epoch", in
>       which each day is accounted for by exactly 86400 seconds, other
>       than that non-integer values can be represented.  See RFC 3339
>       [RFC3339] for details regarding date/times in general and UTC in
>       particular.


> 4.1.4.  "exp" (Expiration Time) Claim
> 
>    The "exp" (expiration time) claim identifies the expiration time on
>    or after which the JWT MUST NOT be accepted for processing.  The
>    processing of the "exp" claim requires that the current date/time
>    MUST be before the expiration date/time listed in the "exp" claim.
> 
>    Implementers MAY provide for some small leeway, usually no more than
>    a few minutes, to account for clock skew.  Its value MUST be a number
>    containing a NumericDate value.  Use of this claim is OPTIONAL.

I'm not opposed to supporting millisecond times if you want to send a PR with tests. I'll otherwise keep it in mind when I'm next working on that area.

**Comment by escardin** [comment]
also just to confirm that the comparison (which is confusing) is correct.
```
var decoded={exp:1484425965097}
var date = new Date(0);
date.setUTCSeconds(decoded.exp);
date.valueOf()
date.toString() //"Wed Aug 02 49009 21:51:37 GMT-0400 (Eastern Daylight Time)"
!(date.valueOf() > (new Date().valueOf())) //false
date.setTime(decoded.exp);
date.toString() //"Sat Jan 14 2017 15:32:45 GMT-0500 (Eastern Standard Time)"
!(date.valueOf() > (new Date().valueOf())) //true
```
So as far as the comparison is conce

**Comment by lukaszwilk** [comment]
Thank you for help, switching to seconds solved my problem.

**Comment by MonkRocker** [comment]
Forgive the necromancy here, but I have run into this same issue, and not sure I am understanding.

If I read you correctly, you are saying that the exp value should be the offset in seconds from the epoch to the expiration date?

That's not how I'm reading the RFC at all.  

> The "exp" (expiration time) claim identifies the expiration time on
or after which the JWT MUST NOT be accepted for processing. The
processing of the "exp" claim requires that the current date/time
MUST be before the expiration date/time listed in the "exp" claim.

That's pretty clearly stating that exp is also a date/time. 

Not really sure why millisecond times aren't the default, since literally every Date method in use here returns milliseconds, not seconds.  Date.getTime(), Date.valueOf(), Date.now().  Those are all in ms, not seconds.  

Could you please clarify?  I am having the same issue @lukaszwilk described.

**Comment by escardin** [comment]
It says specifically that the exp is a NumericDate and a NumericDate is the number of seconds since the epoch (i.e. a unix timestamp). I know that JS's date functions give you millis, It's a pain to have to divide or multiply by 1000 when it's seemingly unnecessary. You don't however, want us guessing at the resolution of your exp as it makes the difference between a expired token and a not expired one.

**Comment by lukaszwilk** [comment]
It's as @escardin said, when using angular2-jwt you need to use seconds for handling exp property. I know it might be confusing and since I've asked this question initially I've working with some systems that used seconds for exp, and others that used milliseconds. You must be elastic and match to requirements/libraries you work with in given project.
