### ISSUE TITLE
Question: unauthenticatedRedirector on angular2/jwt?

### ISSUE THREAD

**Issue by aebmknrl** [auth0/angular2-jwt#325]
Hi, thanks for this excellent work for the comunnity.

On Angular 1 i haved the unauthenticatedRedirector that allows me to redirect the user to the login page when my token are expired. So i used this and i not need to code every request to check if the token are expired or not to redirect the user.

The question is, is there unauthenticatedRedirector on this version? Thanks

**Comment by chenkie** [comment]
Hi @aebmknrl, there isn't a similar method in this library, mostly so we can keep the size small and also because it's tough to anticipate all potential implementations.

I'd recommend creating a method in your `auth` service which can make the check for whether the token is expired or not and then redirect if it is expired. This can then be used in `CanActivate` within your routes.

There are other ways to do this, but that's one example.

**Comment by aebmknrl** [comment]
Ok thanks a lot for taking your time to answer me my friend. 
Best regards,
@aebmknrl
