### ISSUE TITLE
No JWT present or has expired after upgrading to Angular4

### ISSUE THREAD

**Issue by doorman02** [auth0/angular2-jwt#329]
Hi, I am getting this error after updating from Angular 2 to 4 and I am using the latest angular2-jwt

```
AuthHttpError {__zone_symbol__error: Error: No JWT present or has expired
    at AuthHttpError.ZoneAwareError (http://localhost:3000/poly……}
```

I found this [issue](https://github.com/auth0/angular2-jwt/issues/207) but even if I comment out the getter function I still get this error.

```
export function AuthFactory(http: Http, options: RequestOptions) {
    return new AuthHttp(new AuthConfig({
        // tokenName: 'id_token',
        // tokenGetter: (() => localStorage.getItem('id_token')),
        globalHeaders: [{ 'Content-Type': 'application/json' }],
    }), http, options);
};

```
Any idea why I am getting this error?

**Comment by canario** [comment]
How do you fix this  issue?

**Comment by wOOx92** [comment]
How did you fixed this issed?

**Comment by canario** [comment]
I downgraded the version and works fine

**Comment by wOOx92** [comment]
The Angular version, or angular2-jwt version?

**Comment by canario** [comment]
angular2-jwt version

**Comment by wOOx92** [comment]
Thanks! For everyone else getting this error:

angular2-jwt version 0.1.28 + Angular 2.x = working
angular2-jwt version 0.2.x + Angular 4.x = not working
angular2-jwt version 0.1.28 + Angular 4.x = working

**Comment by cwthomas-llu** [comment]
Confirmed that angular2-jwt 0.2.0 works with Angular 4.x

**Comment by sergeu90** [comment]
when this is fixed ?

**Comment by ankit0606** [comment]
Is this fixed? I am  facing same error.

**Comment by Lopierdis** [comment]
Same problem here, downgraded to 0.2.0 and it works, oh well..

**Comment by jjmurre** [comment]
Ran into the same issue. However, even with 0.2.0 I cannot get it to work again.
When setting noClientCheck to true in the config, it works.

```
export function authHttpServiceFactory(http: Http, options: RequestOptions) {
  return new AuthHttp(new AuthConfig({
    noClientCheck: true
  }), http, options)
}
```

**Comment by cwthomas-llu** [comment]
Just check with some co-workers, This problem might be due to the fact that the token name changed from `access_token` to `token` and that you must update your app. Here is the commit where they changed the documentation: a6984d1

**Comment by crooksey** [comment]
On the latest version this can easily be fixed with adding the following inside:

**auth.module.ts**

`export function authHttpServiceFactory(http: Http, options: RequestOptions) {
  return new AuthHttp(new AuthConfig({
    tokenName: 'rawJWT',
    tokenGetter: (() => localStorage.getItem('rawJWT')),
  }), http, options);
}`

Where "rawJWT" is the name the token is stored against inside local browser storage. To find this out, on chrome, go to inspect --> application --> local storage   there you will find the name/key used to store the token inside localstorage.

**Comment by hesampour** [comment]
you are getting this error because you have not set the token correctly for your AuthHttp. your service factory should be something like this
export function authHttpServiceFactory(http: Http, options: RequestOptions,authService:AuthService) {
  return new AuthHttp(new AuthConfig({
    tokenName: 'token',
		tokenGetter: (() => authService.token),
		globalHeaders: [{'Content-Type':'application/json'}],
	}), http, options);
}
I think the best practice is not to get the token from localstorage. but get it from a global service

**Comment by blakecodes** [comment]
I found that the default token name changed on me between versions. I was getting this error because in my app I had the token to register as "sessionToken" while angular2-jwt was trying to find id_token. After changing this it fixed my issue.

`AuthConfigConsts.DEFAULT_TOKEN_NAME = 'id_token';`
