### ISSUE TITLE
jwt assumes a token always exists

### ISSUE THREAD

**Issue by jmls** [auth0/angular2-jwt#336]
I have a need to send a jwt header on *every* request apart from /login, and my app uses some third-party resources , so I thought it would be best to override the standard http service with this

```
import { NgModule } from '@angular/core';
import { Http, RequestOptions,XHRBackend } from '@angular/http';
import { AuthHttp, AuthConfig } from 'angular2-jwt';
import { AuthenticationService } from './auth.service';

export function authHttpServiceFactory(xhrBackend: XHRBackend, options: RequestOptions) {

  return new AuthHttp(new AuthConfig({
    noJwtError:true

  }), new Http(xhrBackend, options), options);
}

@NgModule({

  providers: [
    {
      provide: Http,
      useFactory: authHttpServiceFactory,
      deps: [XHRBackend, RequestOptions]
    },
    AuthenticationService
  ]
})

export class AuthModule {}
```
whilst solving the "all requests must have a jwt header", this creates a real problem when trying to login, as the login post then uses the authHttp service, which then craps out with the error 

```
ERROR TypeError: Cannot read property 'split' of null
    at JwtHelper.decodeToken (angular2-jwt.js:234)
    at JwtHelper.getTokenExpirationDate (angular2-jwt.js:246)
```

as it assumes the token exists

is there a way of specifying *not* to add a token header on certain requests ?

**Comment by msarsha** [comment]
Hey,

Just inject the default `Http` service and not the `AuthHttp`.

`constructor(private http: Http){}`

instead of 

`constructor(private http: AuthHttp){}`

**Comment by michaelkrone** [comment]
I have a similar problem with @auth0/angular-jwt, but since @auth0/angular-jwt is intercepting every request with HttpClient, I am not able to use another Http implementation like suggested by @msarsha.

Using the Http package from @angular/http would be an option but it will be replaced by HttpClient from @angular/common/http, so it will fail sooner or later.

With the current implementation of angular-jwt, how to fetch a token from the server without having one already?
