### ISSUE TITLE
Settings GlobalHeaders breaks Sending Per-Request Headers

### ISSUE THREAD

**Issue by ln-e** [auth0/angular2-jwt#379]
I want all my request send with application/ld+json content-type header. If i set 
```
globalHeaders: [{'Content-Type':'application/ld+json'}],
```

it becomes impossible to override it per request at all
```
let headers = new Headers({'Content-Type': 'multipart/form-data'});
this.http.post('someurl', formData, {headers: headers});
```
Still send application/ld+json

**Comment by bastien612** [comment]
Actually, I think it is a pretty big issue.
I have a big application in production which use "globalHeaders: [{'Content-Type':'application/json'}]". And now, I need to add an upload file feature.
I can't because I can't send a POST request with "Content-Type':'multipart/form-data'". It is not normal that I cannot override the header when I need to.
Now, my only choice is to remove the globalHeader property and add the headers everywhere.
Especially in your documentation, please, don't advise to use this option for "content-type". There are millions of reasons to send something else than json sometime.
