### ISSUE TITLE
Has Global Headers been removed?

### ISSUE THREAD

**Issue by arnvanhoutte** [auth0/angular2-jwt#522]
At the moment my config looks like this:
```

JwtModule.forRoot(({
            config: {
                tokenGetter: () => {
                    return localStorage.getItem('id_token');
                },
                globalHeaders: [{ 'Content-Type': 'application/json' }, { 'Accept': 'application/json' }],
                whitelistedDomains: ['localhost:5555', 'localhost:44373', 'arnvanhoutte.be']
                //blacklistedRoutes: ['localhost:3001/auth/']
            }
        }) as Object),
```

But when I look at my request, the Content-Type is still Plain-Text. Has the global headers option been removed?

**Comment by chenkie** [comment]
It has been removed yeah. It was more useful with older versions of this lib before interceptors were around. Back then, we had to wrap Angular's HTTP calls and global headers made it possible not need to define the headers every time. Since we're now just using an interceptor to attach the token, any kind of HTTP-wide config is left up to the implementer.
