### ISSUE TITLE
Send different tokens based on request

### ISSUE THREAD

**Issue by caraffa** [auth0/angular2-jwt#555]
[Feature request] It would be nice to have to options sent as a parameter to the tokenGetter (like in the angularJS) so that one could decide to send different tokens based on the request uri.

Thanks

**Comment by caraffa** [comment]
I realize right now that this is a duplicate of #551 . 
I was thinking of using the blacklistedRoutes for (manually) sending different header, but I've realized that this is impossible (the tokeGetter is called always)
Therefore this is not a Feature request but a real bug.

**Comment by adammedford** [comment]
Ignoring the bug - I have a similar use case for sending different tokens to different URIs that has kept me from using this. 

@caraffa, I haven't had a chance to test it yet for myself but I think there is an existing solution to this problem - although it has some drawbacks.

Create a dedicated NgModule for each backend URI that you have different token behavior for. In each of those modules import the JwtModule with the configuration for that backend, only not using the forRoot option since it will throw an error. You could just provide the JwtService with the correct configuration but I don't know if those will inject into interceptors correctly. 

The obvious downside to this is that you can't have multiple tokened URIs in the same module. The other being that because you're providing a separate instance per module if you have the same tokened URI in multiple modules they won't share an instance.

Good luck.
