### ISSUE TITLE
JwtModule not attaching authorization token in request

### ISSUE THREAD

**Issue by mdhelaluddin-ctg-bd** [auth0/angular2-jwt#618]
I have configured JwtModule in my Angular app. According to documentation 'Any requests sent using Angular's HttpClient will automatically have a token attached as an Authorization header.' But it's not working ... Can you please check and test the repositories code again?

**Comment by circuitBurn** [comment]
I'm having the same problem. @mdhelaluddin-ctg-bd have you gotten anywhere with it?

**Comment by stevehobbsdev** [comment]
@mdhelaluddin-ctg-bd @circuitBurn  Could you share a repro where we can take a look?

**Comment by BartoszBartniczak** [comment]
@stevehobbsdev I have this same issue.
Here is my repo:
https://github.com/BartoszBartniczak/todo-angular/tree/jwt

If you need API app, here it is:
https://github.com/BartoszBartniczak/symfony-todo-app/tree/jwt

**Comment by stingers** [comment]
I have the same issue. Any solution ?

**Comment by mdhelaluddin-ctg-bd** [comment]
> m having the

Nope. Didn't find any solution.

**Comment by stevehobbsdev** [comment]
@mdhelaluddin-ctg-bd I've noticed in your code that you're using a full origin value in the whitelist array: https://github.com/BartoszBartniczak/todo-angular/blob/jwt/src/app/app.module.ts#L58

Can you try just setting it as `todo-api.test` (without the scheme) and see if that works for you?

**Comment by BartoszBartniczak** [comment]
@stevehobbsdev Your tip was realy helpfull, although it didn't fix the bug at the begining:
![image](https://user-images.githubusercontent.com/6022713/65424827-c3f38100-de0c-11e9-806e-b2d67a3e1607.png)

I needed to change the nginx config and add `Authorization` as accepted header:
`'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization';`

But after that change I couldn't log in:
![image](https://user-images.githubusercontent.com/6022713/65425536-8132a880-de0e-11e9-8919-873d64bcfdcd.png)

I changed the blacklistedRoutes:
```
blacklistedRoutes: [
          'todo-api.test/login_check',
        ],```

which seems to be correct, with documentation, but still doesn't work.

When I turned off the `throwNoTokenError` option, everything started to work, which is a little bit weird.

It looks like, it tries to get token before checking blacklisted routes.

Thank you for your help. Everything working fine right now.
