### ISSUE TITLE
Release v5.1.1 decodeToken<T = any>(token?: string): T | Promise<T>

### ISSUE THREAD

**Issue by sysmat** [auth0/angular2-jwt#757]
### Description

- is this lib using semantic versioning?
- lib bump bug fix version, but it changes type, this more of a braking change
- ng 15 build fails

### Regresion

- it works with 5.1.0
 
### Environment

> Please provide the following:

- "@auth0/angular-jwt": "5.1.1",
- @angular/compiler": "15.0.4";

**Comment by frederikprijck** [comment]
Thanks for reporting. The SDK has always had a public API that made it look like it supported promises to retrieve the token, but it actualy didnt, see #747 .

This has been fixed in the latest patch version. This could break people, but it's fixing incorrect behavior in the SDK so I believe this breaking change is justified in a patch given it's actualy fixing a bug.

**Comment by sysmat** [comment]
ok, @frederikprijck thx for reason

**Comment by frederikprijck** [comment]
Thanks again for reporting, I do believe we made a couple of mistakes with this release, apologies.

Looking into rectifying through https://github.com/auth0/angular2-jwt/pull/759, feel free to have a look.

**Comment by frederikprijck** [comment]
Publish v5.1.2, which should revert some unnecessary breaking changes, but there are still scenario's that will be broken.
