### ISSUE TITLE
[Enhancement] reuse jwtHelper in tokenNotExpired

### ISSUE THREAD

**Issue by sfabriece** [auth0/angular2-jwt#92]
I noticed that your are creating a new JwtHelper everytime tokenNotExpired is called. Can an instance JwtHelper(lazily instantiated) be used instead. Just a thought.

**Comment by escardin** [comment]
I would rather not. It's not an expensive object to create and it would be more code to test. I personally would make tokenNotExpired a method of JwtHelper (among other things).

**Comment by chenkie** [comment]
`tokenNotExpired` should be part of the `JwtHelper` class. This will let it be more easily configurable too. The issue I was running into is that it needs to be a `static` method so it can be used in the `@CanActivate` hook, but this means the class itself has to be reworked since we can't use `this` in a static method to call other methods on the class (such as `isTokenExpired`). If you have any ideas for this let me know, it's on my todo list.

**Comment by escardin** [comment]
We could leave it up to the user to new it in the `@CanActivate` or use Brandon Roberts' injector workaround.

Realistically though, we should just leave it until the final router lands in core.

If we're going to make breaking API changes in that area, We definitely should make JWTHelper injectable and have it use AuthConfig. AuthHttp probably should depend on JWTHelper as well. Something like that anyway.

**Comment by chenkie** [comment]
That's my thinking too 👍 Thanks

**Comment by sfabriece** [comment]
Sounds like the way to go :+1: Awesome lib btw.
